export const CARD_EFFECTS: Record<number, string> = {
  0: "Next answer auto-correct, 0 points.",
  1: "Discard current question, draw a new one. If no replacement exists, slot is not spent.",
  2: "MCQ: eliminate one wrong option. TF: hints at lean.",
  3: "Restore 20 HP immediately.",
  4: "Next wrong answer deals half damage.",
  5: "Next correct answer: +5 bonus boss damage (true damage vs Chop’s shield).",
  6: "Next correct = double boss damage; next wrong = double self-damage.",
  7: "Next correct = +10 bonus damage; next wrong = +5 extra self-damage.",
  8: "Next wrong answer deals 0 damage.",
  9: "Swap current question for a lower-tier one. If none available, slot is not spent.",
  10: "Random effect: heal 10, self-damage 10, free skip, or double-or-nothing.",
  11: "Replace current question with True/False. If none available, slot is not spent.",
  12: "Pay 5 HP. Extra time to read before the timer counts down.",
  13: "Deal 10 true damage to boss (bypasses shield).",
  14: "Next wrong: split damage 50/50 between you and the boss.",
  15: "Next 2 questions: correct +50% boss damage, wrong +50% self-damage.",
  16: "Remove Chop's shield entirely. Or deal 15 direct damage.",
  17: "If HP < 40: restore to 40. Otherwise heal 10.",
  18: "Hide a keyword in the question. If still correct: +20 bonus damage.",
  19: "MCQ or True/False: highlight the correct choice's border.",
  20: "Passive: auto-revives you once if HP reaches 0. Cannot be activated manually.",
  21: "Next answer auto-correct, half points.",
};

export const CARD_FLAVOR_LINES: Record<number, string> = {
  0:  "Flying blind. On purpose.",
  1:  "Burning the question. Drawing a better one.",
  2:  "Cutting the noise. One option down.",
  3:  "HP restored. Back in the fight.",
  4:  "Absorbing half the blow.",
  5:  "Blessing the next strike: extra bite on the boss.",
  6:  "Double or nothing. My call.",
  7:  "Momentum locked in.",
  8:  "Take the hit. Don't flinch.",
  9:  "Swapping for something simpler.",
  10: "Spinning the wheel. No guarantees.",
  11: "Forcing true or false. Odds evened.",
  12: "Five seconds to read. Burning HP for it.",
  13: "Ten true damage. Bypasses everything.",
  14: "Split the damage. Shared pain.",
  15: "Two rounds of chaos. Here we go.",
  16: "Shield gone. All of it.",
  17: "Back above 40. Breathing room.",
  18: "Keyword hidden. Extra damage if I still get it.",
  19: "Correct answer outlined. Clean read.",
  20: "Passive. It revives me once.",
  21: "Auto-correct. Half the points. Worth it.",
};
